global_params: # Every drive will get one of these
  # Naming every type of internal state
  optimal_internal_state:
    food: 
      value:  0
      loss: 0.003
      intake: 0.1
    water: 
      value:  0.3
      loss: 0.003
      intake: 0.1
    energy: 
      value:  0.6
      loss: 0.003
      intake: 0.1
    temperature:
      value:  0.8
      loss: 0.003
      intake: 0.1

drive_params:

  # Base drive configs
  base_drive:
    n: 3
    m: 2

  # Elliptic drive configs
  elliptic_drive:
    n_vector: [4, 3, 2, 5]

  # Interoceptive drive configs
  interoceptive_drive:
    eta: 2.0
  
