global_params: # Every drive will get one of these
  # Naming every type of internal state
  optimal_internal_state:
    food: 4
    water: 2

drive_params:

  # Base drive configs
  base_drive:
    n: 4
    m: 3

  # Elliptic drive configs
  elliptic_drive:
    n_vector: [4, 6]

  # Interoceptive drive configs
  interoceptive_drive:
    eta: 0.1
  
