global_params: # Every drive will get one of these
  # Naming every type of internal state
  optimal_internal_state:
    food: 1.5
    water: 2.5
    temperature: 1.0
    energy: 3.0

drive_params:
  # Base drive configs
  base_drive:
    n: 3
    m: 4

  # Elliptic drive configs
  elliptic_drive:
    n_vector: [3, 4, 2, 5]
    m: 5

  # Interoceptive drive configs
  interoceptive_drive:
    eta: 0.7
